CREATE TABLE CLIENT (
    ID          INT             PRIMARY KEY AUTO_INCREMENT,
    USERNAME    VARCHAR(200)    NOT NULL    UNIQUE
);

CREATE TABLE MESSAGE (
    ID          INT             PRIMARY KEY AUTO_INCREMENT,
    SENT_AT     DATETIME        NOT NULL    DEFAULT CURRENT_DATE(),
    SENDER      INT             NOT NULL,
    RECIPIENT   INT             NOT NULL,
    TEXT        VARCHAR(200)    NOT NULL,

    FOREIGN KEY (SENDER)    REFERENCES CLIENT(ID),
    FOREIGN KEY (RECIPIENT) REFERENCES CLIENT(ID)
);